### ISSUE TITLE
pip artifact is not up to date

### ISSUE THREAD

**Issue by daniel86** [tilde-lab/pyfactxx#16]
Hello,

Loading an ontology fails with published pip artifact:
```
>>> crs.load(owfile)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/daniel/.local/lib/python3.10/site-packages/pyfactxx/coras/core.py", line 50, in load
    self._graph.load(f, format=format)
AttributeError: 'ConjunctiveGraph' object has no attribute 'load'
```

In fact, `core.py` in the source tree rather uses *parse* method, changing it in the file fixes the loading error.

**Comment by blokhin** [comment]
@daniel86 many thanks, will fix asap

**Comment by blokhin** [comment]
@irygaev is this exactly what you have mentioned recently?

**Comment by irygaev** [comment]
Yes, that's the one. The pip package needs to be rebuilt from the latest code.
